// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: space.proto

package spaceservice

import (
	"context"

	"picture/rpc/space-rpc/space"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSpaceMemberRequest    = space.AddSpaceMemberRequest
	AddSpaceMemberResponse   = space.AddSpaceMemberResponse
	CreateSpaceRequest       = space.CreateSpaceRequest
	CreateSpaceResponse      = space.CreateSpaceResponse
	GetSpaceAnalysisRequest  = space.GetSpaceAnalysisRequest
	GetSpaceAnalysisResponse = space.GetSpaceAnalysisResponse
	GetSpaceRequest          = space.GetSpaceRequest
	GetSpaceResponse         = space.GetSpaceResponse
	ListSpaceMembersRequest  = space.ListSpaceMembersRequest
	ListSpaceMembersResponse = space.ListSpaceMembersResponse
	SpaceMember              = space.SpaceMember
	SpaceUsageTrend          = space.SpaceUsageTrend
	UpdateSpaceUsageRequest  = space.UpdateSpaceUsageRequest
	UpdateSpaceUsageResponse = space.UpdateSpaceUsageResponse

	SpaceService interface {
		// 创建空间
		CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*CreateSpaceResponse, error)
		// 获取空间信息
		GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*GetSpaceResponse, error)
		// 添加空间成员
		AddSpaceMember(ctx context.Context, in *AddSpaceMemberRequest, opts ...grpc.CallOption) (*AddSpaceMemberResponse, error)
		// 获取空间成员列表
		ListSpaceMembers(ctx context.Context, in *ListSpaceMembersRequest, opts ...grpc.CallOption) (*ListSpaceMembersResponse, error)
		// 更新空间使用容量
		UpdateSpaceUsage(ctx context.Context, in *UpdateSpaceUsageRequest, opts ...grpc.CallOption) (*UpdateSpaceUsageResponse, error)
		// 获取空间分析数据
		GetSpaceAnalysis(ctx context.Context, in *GetSpaceAnalysisRequest, opts ...grpc.CallOption) (*GetSpaceAnalysisResponse, error)
	}

	defaultSpaceService struct {
		cli zrpc.Client
	}
)

func NewSpaceService(cli zrpc.Client) SpaceService {
	return &defaultSpaceService{
		cli: cli,
	}
}

// 创建空间
func (m *defaultSpaceService) CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*CreateSpaceResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.CreateSpace(ctx, in, opts...)
}

// 获取空间信息
func (m *defaultSpaceService) GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*GetSpaceResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.GetSpace(ctx, in, opts...)
}

// 添加空间成员
func (m *defaultSpaceService) AddSpaceMember(ctx context.Context, in *AddSpaceMemberRequest, opts ...grpc.CallOption) (*AddSpaceMemberResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.AddSpaceMember(ctx, in, opts...)
}

// 获取空间成员列表
func (m *defaultSpaceService) ListSpaceMembers(ctx context.Context, in *ListSpaceMembersRequest, opts ...grpc.CallOption) (*ListSpaceMembersResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.ListSpaceMembers(ctx, in, opts...)
}

// 更新空间使用容量
func (m *defaultSpaceService) UpdateSpaceUsage(ctx context.Context, in *UpdateSpaceUsageRequest, opts ...grpc.CallOption) (*UpdateSpaceUsageResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.UpdateSpaceUsage(ctx, in, opts...)
}

// 获取空间分析数据
func (m *defaultSpaceService) GetSpaceAnalysis(ctx context.Context, in *GetSpaceAnalysisRequest, opts ...grpc.CallOption) (*GetSpaceAnalysisResponse, error) {
	client := space.NewSpaceServiceClient(m.cli.Conn())
	return client.GetSpaceAnalysis(ctx, in, opts...)
}
