// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"picture/api/space-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建空间
				Method:  http.MethodPost,
				Path:    "/space",
				Handler: createSpaceHandler(serverCtx),
			},
			{
				// 获取空间信息
				Method:  http.MethodGet,
				Path:    "/space/:id",
				Handler: getSpaceHandler(serverCtx),
			},
			{
				// 更新空间信息
				Method:  http.MethodPut,
				Path:    "/space/:id",
				Handler: updateSpaceHandler(serverCtx),
			},
			{
				// 删除空间
				Method:  http.MethodDelete,
				Path:    "/space/:id",
				Handler: deleteSpaceHandler(serverCtx),
			},
			{
				// 获取空间分析数据
				Method:  http.MethodGet,
				Path:    "/space/:id/analysis",
				Handler: getSpaceAnalysisHandler(serverCtx),
			},
			{
				// 获取空间信息（封装类）
				Method:  http.MethodGet,
				Path:    "/space/:id/vo",
				Handler: getSpaceVOHandler(serverCtx),
			},
			{
				// 获取空间列表
				Method:  http.MethodGet,
				Path:    "/space/list",
				Handler: listSpaceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
