Server:
  Name: go-picture
  Mode: dev
  Port: 8888

MySQL:
  DataSource: root:Mima4256.@tcp(localhost:3306)/picture?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

JWT:
  AccessSecret: your-secret-key
  AccessExpire: 86400

Storage:
  Type: local
  LocalPath: ./storage
  MaxFileSize: 10485760  # 10MB

Redis:
  Host: localhost:6379
  Type: node
  Pass: ""