// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package userservice

import (
	"context"

	"picture/rpc/user-rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResponse       = user.BaseResponse
	DeleteUserRequest  = user.DeleteUserRequest
	GetUserByIdRequest = user.GetUserByIdRequest
	LoginRequest       = user.LoginRequest
	LoginResponse      = user.LoginResponse
	LogoutRequest      = user.LogoutRequest
	RegisterRequest    = user.RegisterRequest
	RegisterResponse   = user.RegisterResponse
	UserAddRequest     = user.UserAddRequest
	UserInfo           = user.UserInfo
	UserQueryRequest   = user.UserQueryRequest
	UserQueryResponse  = user.UserQueryResponse
	UserUpdateRequest  = user.UserUpdateRequest

	UserService interface {
		// 基础功能
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetCurrentUser(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		// 用户管理功能
		AddUser(ctx context.Context, in *UserAddRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		UpdateUser(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*BaseResponse, error)
		ListUserByPage(ctx context.Context, in *UserQueryRequest, opts ...grpc.CallOption) (*UserQueryResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 基础功能
func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) GetCurrentUser(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 用户管理功能
func (m *defaultUserService) AddUser(ctx context.Context, in *UserAddRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUser(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserService) ListUserByPage(ctx context.Context, in *UserQueryRequest, opts ...grpc.CallOption) (*UserQueryResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ListUserByPage(ctx, in, opts...)
}
