// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: picture.proto

package server

import (
	"context"

	"picture/rpc/picture-rpc/internal/logic"
	"picture/rpc/picture-rpc/internal/svc"
	"picture/rpc/picture-rpc/picture"
)

type PictureServiceServer struct {
	svcCtx *svc.ServiceContext
	picture.UnimplementedPictureServiceServer
}

func NewPictureServiceServer(svcCtx *svc.ServiceContext) *PictureServiceServer {
	return &PictureServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传图片
func (s *PictureServiceServer) UploadPicture(ctx context.Context, in *picture.UploadPictureRequest) (*picture.UploadPictureResponse, error) {
	l := logic.NewUploadPictureLogic(ctx, s.svcCtx)
	return l.UploadPicture(in)
}

// 获取图片信息
func (s *PictureServiceServer) GetPicture(ctx context.Context, in *picture.GetPictureRequest) (*picture.GetPictureResponse, error) {
	l := logic.NewGetPictureLogic(ctx, s.svcCtx)
	return l.GetPicture(in)
}

// 编辑图片
func (s *PictureServiceServer) EditPicture(ctx context.Context, in *picture.EditPictureRequest) (*picture.EditPictureResponse, error) {
	l := logic.NewEditPictureLogic(ctx, s.svcCtx)
	return l.EditPicture(in)
}

// 删除图片
func (s *PictureServiceServer) DeletePicture(ctx context.Context, in *picture.DeletePictureRequest) (*picture.DeletePictureResponse, error) {
	l := logic.NewDeletePictureLogic(ctx, s.svcCtx)
	return l.DeletePicture(in)
}

// 图片审核
func (s *PictureServiceServer) ReviewPicture(ctx context.Context, in *picture.ReviewPictureRequest) (*picture.ReviewPictureResponse, error) {
	l := logic.NewReviewPictureLogic(ctx, s.svcCtx)
	return l.ReviewPicture(in)
}

// 批量编辑图片
func (s *PictureServiceServer) EditPictureByBatch(ctx context.Context, in *picture.EditPictureByBatchRequest) (*picture.EditPictureByBatchResponse, error) {
	l := logic.NewEditPictureByBatchLogic(ctx, s.svcCtx)
	return l.EditPictureByBatch(in)
}

// 分页获取图片列表
func (s *PictureServiceServer) ListPicture(ctx context.Context, in *picture.ListPictureRequest) (*picture.ListPictureResponse, error) {
	l := logic.NewListPictureLogic(ctx, s.svcCtx)
	return l.ListPicture(in)
}
