// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: space.proto

package server

import (
	"context"

	"picture/rpc/space-rpc/internal/logic"
	"picture/rpc/space-rpc/internal/svc"
	"picture/rpc/space-rpc/space"
)

type SpaceServiceServer struct {
	svcCtx *svc.ServiceContext
	space.UnimplementedSpaceServiceServer
}

func NewSpaceServiceServer(svcCtx *svc.ServiceContext) *SpaceServiceServer {
	return &SpaceServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建空间
func (s *SpaceServiceServer) CreateSpace(ctx context.Context, in *space.CreateSpaceRequest) (*space.CreateSpaceResponse, error) {
	l := logic.NewCreateSpaceLogic(ctx, s.svcCtx)
	return l.CreateSpace(in)
}

// 获取空间信息
func (s *SpaceServiceServer) GetSpace(ctx context.Context, in *space.GetSpaceRequest) (*space.GetSpaceResponse, error) {
	l := logic.NewGetSpaceLogic(ctx, s.svcCtx)
	return l.GetSpace(in)
}

// 添加空间成员
func (s *SpaceServiceServer) AddSpaceMember(ctx context.Context, in *space.AddSpaceMemberRequest) (*space.AddSpaceMemberResponse, error) {
	l := logic.NewAddSpaceMemberLogic(ctx, s.svcCtx)
	return l.AddSpaceMember(in)
}

// 获取空间成员列表
func (s *SpaceServiceServer) ListSpaceMembers(ctx context.Context, in *space.ListSpaceMembersRequest) (*space.ListSpaceMembersResponse, error) {
	l := logic.NewListSpaceMembersLogic(ctx, s.svcCtx)
	return l.ListSpaceMembers(in)
}

// 更新空间使用容量
func (s *SpaceServiceServer) UpdateSpaceUsage(ctx context.Context, in *space.UpdateSpaceUsageRequest) (*space.UpdateSpaceUsageResponse, error) {
	l := logic.NewUpdateSpaceUsageLogic(ctx, s.svcCtx)
	return l.UpdateSpaceUsage(in)
}

// 获取空间分析数据
func (s *SpaceServiceServer) GetSpaceAnalysis(ctx context.Context, in *space.GetSpaceAnalysisRequest) (*space.GetSpaceAnalysisResponse, error) {
	l := logic.NewGetSpaceAnalysisLogic(ctx, s.svcCtx)
	return l.GetSpaceAnalysis(in)
}
