// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	admin "picture/api/user-api/internal/handler/admin"
	"picture/api/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Admin},
			[]rest.Route{
				{
					// 创建用户
					Method:  http.MethodPost,
					Path:    "/user/add",
					Handler: admin.AddUserHandler(serverCtx),
				},
				{
					// 删除用户
					Method:  http.MethodPost,
					Path:    "/user/delete/:id",
					Handler: admin.DeleteUserHandler(serverCtx),
				},
				{
					// 分页获取用户列表
					Method:  http.MethodPost,
					Path:    "/user/list/page",
					Handler: admin.ListUserByPageHandler(serverCtx),
				},
				{
					// 更新用户
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: admin.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
