// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddSpaceMemberReq struct {
	UserId int64  `json:"userId"`
	Role   string `json:"role"`
}

type AddSpaceMemberResp struct {
	Success bool `json:"success"`
}

type CreateSpaceReq struct {
	SpaceName  string `json:"spaceName"`
	SpaceDesc  string `json:"spaceDesc,optional"`
	SpaceType  string `json:"spaceType"`
	SpaceLevel string `json:"spaceLevel"`
}

type CreateSpaceResp struct {
	Id int64 `json:"id"`
}

type GetSpaceResp struct {
	Id            int64  `json:"id"`
	SpaceName     string `json:"spaceName"`
	SpaceDesc     string `json:"spaceDesc"`
	SpaceType     string `json:"spaceType"`
	SpaceLevel    string `json:"spaceLevel"`
	UserId        int64  `json:"userId"`
	TotalCapacity int64  `json:"totalCapacity"`
	UsedCapacity  int64  `json:"usedCapacity"`
	CreateTime    string `json:"createTime"`
	UpdateTime    string `json:"updateTime"`
}

type ListSpaceMembersResp struct {
	Members []SpaceMemberInfo `json:"members"`
}

type SpaceMemberInfo struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	UserName   string `json:"userName"`
	UserAvatar string `json:"userAvatar"`
	Role       string `json:"role"`
	JoinTime   string `json:"joinTime"`
}

type UpdateSpaceUsageReq struct {
	Size      int64  `json:"size"`
	Operation string `json:"operation"`
}

type UpdateSpaceUsageResp struct {
	Success           bool  `json:"success"`
	RemainingCapacity int64 `json:"remainingCapacity"`
}
