// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CategoryCount struct {
	Category  string `json:"category"`
	Count     int64  `json:"count"`
	TotalSize int64  `json:"totalSize"`
}

type CreateSpaceReq struct {
	SpaceName  string `json:"spaceName"`
	SpaceType  int32  `json:"spaceType"`  // 0-私有 1-团队
	SpaceLevel int32  `json:"spaceLevel"` // 0-普通版 1-专业版 2-旗舰版
}

type ListReq struct {
	Current   int64  `form:"current,default=1"`
	PageSize  int64  `form:"pageSize,default=10"`
	SpaceName string `form:"spaceName,optional"`
	SpaceType int32  `form:"spaceType,optional"`
}

type ListSpaceResp struct {
	List     []SpaceInfo `json:"list"`
	Total    int64       `json:"total"`
	Current  int64       `json:"current"`
	PageSize int64       `json:"pageSize"`
}

type ListSpaceVOResp struct {
	List     []SpaceVO `json:"list"`
	Total    int64     `json:"total"`
	Current  int64     `json:"current"`
	PageSize int64     `json:"pageSize"`
}

type SizeCount struct {
	SizeRange string `json:"sizeRange"`
	Count     int64  `json:"count"`
}

type SpaceAnalysis struct {
	Usage     SpaceUsage      `json:"usage"`
	Category  []CategoryCount `json:"category"`
	Tags      []TagCount      `json:"tags"`
	SizeRange []SizeCount     `json:"sizeRange"`
}

type SpaceAnalysisReq struct {
	SpaceId   int64  `json:"spaceId"`
	TimeRange string `json:"timeRange,optional"` // day/week/month
}

type SpaceInfo struct {
	Id         int64  `json:"id"`
	SpaceName  string `json:"spaceName"`
	SpaceType  int32  `json:"spaceType"`  // 0-私有 1-团队
	SpaceLevel int32  `json:"spaceLevel"` // 0-普通版 1-专业版 2-旗舰版
	MaxSize    int64  `json:"maxSize"`
	MaxCount   int64  `json:"maxCount"`
	TotalSize  int64  `json:"totalSize"`
	TotalCount int64  `json:"totalCount"`
	UserId     int64  `json:"userId"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type SpaceUsage struct {
	UsedSize        int64   `json:"usedSize"`
	MaxSize         int64   `json:"maxSize"`
	SizeUsageRatio  float64 `json:"sizeUsageRatio"`
	UsedCount       int64   `json:"usedCount"`
	MaxCount        int64   `json:"maxCount"`
	CountUsageRatio float64 `json:"countUsageRatio"`
}

type SpaceVO struct {
	SpaceInfo
	UserInfo
	Permissions []string `json:"permissions,optional"`
}

type TagCount struct {
	Tag   string `json:"tag"`
	Count int64  `json:"count"`
}

type UpdateSpaceReq struct {
	Id         int64  `path:"id"`
	SpaceName  string `json:"spaceName,optional"`
	SpaceLevel int32  `json:"spaceLevel,optional"`
	MaxSize    int64  `json:"maxSize,optional"`
	MaxCount   int64  `json:"maxCount,optional"`
}

type UserInfo struct {
	Id         int64  `json:"id"`
	UserName   string `json:"username"`
	UserAvatar string `json:"userAvatar"`
	UserRole   string `json:"userRole"`
}
